export interface ModifierInfo {
    title: string;
    description: string;
    minValue: number;
    maxValue: number;
    type: '前缀' | '后缀';
}

export const modifierInfoList: ModifierInfo[] = [
    {
        title: '怪物的强度提高',
        description: '怪物的强度提高 #%',
        minValue: 10,
        maxValue: 15,
        type: '前缀',
    },
    {
        title: '获取物品的稀有度提高',
        description: '地图内获取物品的稀有度提高 #%',
        minValue: 8,
        maxValue: 12,
        type: '前缀',
    },
    {
        title: '怪物群规模提高',
        description: '地图内怪物群规模提高 #%',
        minValue: 5,
        maxValue: 7,
        type: '前缀',
    },
    {
        title: '魔法怪物数量提高',
        description: '地图内魔法怪物数量提高 #%',
        minValue: 30,
        maxValue: 40,
        type: '前缀',
    },
    {
        title: '稀有怪物数量提高',
        description: '地图内稀有怪物数量提高 #%',
        minValue: 25,
        maxValue: 35,
        type: '前缀',
    },
    {
        title: '怪物稀有度提高',
        description: '地图上的怪物稀有度提高 #%',
        minValue: 15,
        maxValue: 20,
        type: '前缀',
    },
    {
        title: '金币数量提高',
        description: '地图内找到的金币数量提高 #%',
        minValue: 25,
        maxValue: 35,
        type: '前缀',
    },
    {
        title: '经验值获取提高',
        description: '地图内的经验值获取提高 #%',
        minValue: 12,
        maxValue: 18,
        type: '前缀',
    },
    {
        title: '额外的稀有宝箱',
        description: '地图包含 # 个额外的稀有宝箱',
        minValue: 2,
        maxValue: 3,
        type: '前缀',
    },
    {
        title: '包含一个额外的精华',
        description: '地图包含一个额外的精华',
        minValue: 1,
        maxValue: 1,
        type: '前缀',
    },
    {
        title: '额外的阿兹莫里之灵',
        description: '地图包含 # 个额外的阿兹莫里之灵',
        minValue: 1,
        maxValue: 1,
        type: '前缀',
    },
    {
        title: '额外的盗贼流放者',
        description: '地图内会出现 1 个额外的盗贼流放者',
        minValue: 1,
        maxValue: 1,
        type: '前缀',
    },
    {
        title: '地图包含一个额外的召唤法阵',
        description: '地图包含一个额外的召唤法阵',
        minValue: 1,
        maxValue: 1,
        type: '前缀',
    },
    {
        title: '找到的引路石数量提高',
        description: '地图内找到的引路石数量提高 #%',
        minValue: 30,
        maxValue: 40,
        type: '后缀',
    },
    {
        title: '神龛的几率提高',
        description: '地图包含神龛的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '一个额外的神龛',
        description: '地图包含一个额外的神龛',
        minValue: 1,
        maxValue: 1,
        type: '后缀',
    },
    {
        title: '保险箱的几率提高',
        description: '地图包含保险箱的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '一个额外的保险箱',
        description: '地图包含一个额外的保险箱',
        minValue: 1,
        maxValue: 1,
        type: '后缀',
    },
    {
        title: '精华的几率提高',
        description: '地图包含精华的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '阿兹莫里之灵的几率提高',
        description: '地图包含阿兹莫里之灵的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '盗贼流放者的几率提高',
        description: '地图包含盗贼流放者的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '召唤法阵的几率提高',
        description: '地图包含召唤法阵的几率提高 #%',
        minValue: 70,
        maxValue: 100,
        type: '后缀',
    },
    {
        title: '额外的随机词缀',
        description: '地图拥有 # 个额外的随机词缀',
        minValue: 1,
        maxValue: 2,
        type: '后缀',
    },
    {
        title: '传奇怪物额外具有 1 个词缀',
        description: '传奇怪物额外具有 # 个词缀',
        minValue: 1,
        maxValue: 1,
        type: '后缀',
    },
    {
        title: '深渊生成的怪物数量提高',
        description: '地图中的深渊生成的怪物数量提高 #%',
        minValue: 20,
        maxValue: 30,
        type: '后缀',
    },
    {
        title: '深渊额外生成',
        description: '地图中的深渊额外生成 # 个稀有怪物',
        minValue: 1,
        maxValue: 2,
        type: '后缀',
    },
    {
        title: '深渊怪物的强度',
        description:
            '每关闭一个巨坑，深渊怪物的强度提高 #%，最高可达 100%',
        minValue: 8,
        maxValue: 12,
        type: '后缀',
    },
    {
        title: '绝望深渊的几率提高',
        description: '地图中的深渊通往绝望深渊的几率提高 #%',
        minValue: 10,
        maxValue: 20,
        type: '后缀',
    },
    {
        title: '地图额外包含一个深渊',
        description: '地图额外包含一个深渊',
        minValue: 1,
        maxValue: 1,
        type: '后缀',
    },
    {
        title: '地图中的深渊巨坑有双倍几率有奖励',
        description: '地图中的深渊巨坑有双倍几率有奖励',
        minValue: 1,
        maxValue: 1,
        type: '后缀',
    },
    {
        title: '额外包含四个深渊',
        description: '地图有 #% 的几率额外包含四个深渊',
        minValue: 20,
        maxValue: 40,
        type: '后缀',
    },
    {
        title: '深渊怪物带有深渊词缀的几率提高',
        description: '地图中的深渊怪物带有深渊词缀的几率提高 #%',
        minValue: 20,
        maxValue: 30,
        type: '后缀',
    },
    {
        title: '深渊掉落渎灵通货的几率提高',
        description: '地图中的深渊掉落渎灵通货的几率提高 #%',
        minValue: 20,
        maxValue: 30,
        type: '后缀',
    },
];
